### ISSUE TITLE
Add SecureSocketOption StartTls

### ISSUE THREAD

**Issue by StonyCow** [NLog/NLog.MailKit#13]
I have some trouble with the ssl handshake to smtp server:

> 2017-06-13 08:59:32.5148 Error Error sending mail. Exception: System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
   at NLog.MailKit.MailTarget.ProcessSingleMailMessage(IList`1 events)

The solution I found was to start TLS with the secure socket option:
`client.Connect(renderedHost, SmtpPort, SecureSocketOptions.StartTls);`

Is it possible to get this into your project?

**Comment by 304NotModified** [comment]
Sure, 

Do you think we need a new config setting or could we reuse an existing?

**Comment by 304NotModified** [comment]
I think just adding a new config setting `enableStartTls`, right?

**Comment by 304NotModified** [comment]
or exposing http://www.mimekit.net/docs/html/T_MailKit_Security_SecureSocketOptions.htm

**Comment by 304NotModified** [comment]
What's your current config? I see in the docs:

> even if the useSsl parameter is false, SSL/TLS may still be used if the mail server supports the STARTTLS extension.

http://www.mimekit.net/docs/html/M_MailKit_MailService_Connect_1.htm

so disable "enableSSL" should work?

**Comment by 304NotModified** [comment]
@StonyCow bump

**Comment by 304NotModified** [comment]
disable "enableSSL" should work

Closing this due inactivity

**Comment by neilmulhy** [comment]
I'm having the same issue as @StonyCow whilst trying to configure my error logs to be sent via Office 365 mail.

@304NotModified could I ask that this issue be opened back up?

For your information, changing the enableSSL="false" doesn't work in NLog.Extensions.Logging 1.0.0-rtm-rc2 with NLog.MailKit 2.0.0.

I basically need to be able to configure the following call in MailKit so that nlog can successfully handshake with Office 365:
client.Connect(SmtpServer, SmtpPortNumber, **SecureSocketOptions.StartTls**);

**Comment by 304NotModified** [comment]
Please post your internal log. Thanks!

**Comment by neilmulhy** [comment]
**If I have enableSsl ="false" set in nlog.config**
2017-11-22 21:15:39.2171 Error Error sending mail. Exception: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Stream transport, Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslStreamInternal.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStreamInternal.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStreamInternal.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, BufferAsyncResult asyncResult)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MailKit.Net.Smtp.SmtpStream.ReadAhead(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendCommand(String command, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at NLog.MailKit.MailTarget.ProcessSingleMailMessage(IList`1 events)

**If I have enableSsl ="true" set in nlog.config**
2017-11-22 21:19:51.1632 Error Error sending mail. Exception: System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
   at NLog.MailKit.MailTarget.ProcessSingleMailMessage(IList`1 events)

Thank you!

**Comment by 304NotModified** [comment]
OK thanks!

**Comment by 304NotModified** [comment]
working on this!

**Comment by 304NotModified** [comment]
nlog.mailkit 2.1  is in the deploy queue!

**Comment by neilmulhy** [comment]
Great work @304NotModified! I'll get this installed tomorrow and try it out! Thanks for your help!

**Comment by neilmulhy** [comment]
Hi @304NotModified,

I've installed nlog.mailkit v2.1.0 into my project, tried re-building, then tried clearing the bin folder and re-building but It's still trying to connection via MailKit.Net.Smtp.SmtpClient.Connect.

![image](https://user-images.githubusercontent.com/33902835/33178792-2ef61d0e-d05f-11e7-884c-4ec082996266.png)

I have enableSsl = "true" in my nlog.config file.

Am I missing anything here?

**Internal Log**
2017-11-23 14:54:15.5475 Error Error sending mail. Exception: System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at **MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)**
   at NLog.MailKit.MailTarget.ProcessSingleMailMessage(IList`1 events)

**Comment by 304NotModified** [comment]
there is a new option, did you use that one?

> secureSocketOption - Only in NLog.Mailkit 2.1+. Provides a way of specifying the SSL and/or TLS encryption. Default StartTlsWhenAvailable. Options: None, Auto, SslOnConnect, StartTls & StartTlsWhenAvailable. If enableSsl is set to true, SslOnConnect will be used

see https://github.com/NLog/NLog/wiki/Mail-Target#smtp-options

**Comment by 304NotModified** [comment]
Start TLS <> SSL ;) So EnableSSL should be false (or omitted) at least

**Comment by neilmulhy** [comment]
Thanks for that @304NotModified.

I've removed the enabledSsl attribute from config and get a different error now if I set secureSocketOption to StartTls, StartTlsWhenAvailable or Auto.

I've tried using port 25 and 587 but it makes no difference.

**Extract from internal log**
2017-11-23 15:48:56.1639 Error Error sending mail. Exception: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Stream transport, Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslStreamInternal.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStreamInternal.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStreamInternal.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, BufferAsyncResult asyncResult)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MailKit.Net.Smtp.SmtpStream.ReadAhead(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendCommand(String command, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at NLog.MailKit.MailTarget.ProcessSingleMailMessage(IList`1 events)

For reference a test c# example I get working is included below:

`public void SendEmail()
        {
            try
            {
                //From Address 
                string FromAddress = "foo@foo.com";
                string FromAdressTitle = "Foo";
                //To Address 
                string ToAddress = "foo2@foo.com";
                string ToAdressTitle = "Foo2";
                string Subject = "Hello World - Sending email using ASP.NET Core 2.0";
                string BodyContent = "Test content for Hello world.";

                //Smtp Server 
                string SmtpServer = "smtp.office365.com";
                //Smtp Port Number 
                int SmtpPortNumber = 25;

                var mimeMessage = new MimeMessage();
                mimeMessage.From.Add(new MailboxAddress(FromAdressTitle, FromAddress));
                mimeMessage.To.Add(new MailboxAddress(ToAdressTitle, ToAddress));
                mimeMessage.Subject = Subject;
                mimeMessage.Body = new TextPart("plain")
                {
                    Text = BodyContent

                };

                using (var client = new SmtpClient())
                {

                    client.Connect(SmtpServer, SmtpPortNumber, **SecureSocketOptions.StartTls**);
                    // Note: only needed if the SMTP server requires authentication 
                    // Error 5.5.1 Authentication  
                    client.Authenticate("office365username", "office365password");
                    client.Send(mimeMessage);
                    client.Disconnect(true);

                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }`

**Comment by 304NotModified** [comment]
could you please check if the option is logged correctly to the internal log? see https://github.com/NLog/NLog.MailKit/blob/master/src/NLog.MailKit/MailTarget.cs#L351

**Comment by neilmulhy** [comment]
Sorry, GitHub nube! Thanks for formatting it better!

I've changed my internalLogLevel to Debug and can see that it does output the sending email. See below:

2017-11-23 20:23:39.9766 Debug Sending mail to foo@foo.com using smtp.office365.com:25 (socket option=StartTls)
2017-11-23 20:23:39.9766 Trace   Subject: 'Error on website'
2017-11-23 20:23:39.9829 Trace   From: 'foo@foo.com'
2017-11-23 20:23:40.6252 Trace   Connecting succesfull
2017-11-23 20:23:40.6252 Debug Authenticate with username 'foo@foo.com'

The next line logged is the error:
2017-11-23 20:23:41.8536 Error Error sending mail. Exception: System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by neilmulhy** [comment]
Hi @304NotModified - any progress on this or anything to suggest I try?

**Comment by 304NotModified** [comment]
thanks for the reminder!

No i have not. And honestly I don't know how to test this.


Also the code in the mailtarget is the almost the same are your example? (
https://github.com/NLog/NLog.MailKit/issues/13#issuecomment-346654145)?

vs https://github.com/NLog/NLog.MailKit/blob/master/src/NLog.MailKit/MailTarget.cs#L350-L380

**Comment by neilmulhy** [comment]
I've tried the following in my test routine and it still sends the email okay:

1) Set the timeout to your default
client.Timeout = 10000;
2) Used the authenticate method encoding UTF8 explicitly passed over
client.Authenticate(Encoding.UTF8, "office365user", "officer365password");
3) Tried removing the XOAUTH2 authentication mechanism:
client.AuthenticationMechanisms.Remove("XOAUTH2");
4) Changed the secure socket option to starttlswhenavailable as part of the smtp connect
SecureSocketOptions.StartTlsWhenAvailable

Then the following which gave the expected errors:
1) Even though the internal debug stack I put above showed that it tried to authenticate, I tried remming out this line but I got an expected error about not being able to send anonymous email.

2) Tried just to submit an invalid password and again got an expected error 5.7.3 Authentication unsuccessful MailKit.Security.AuthenticationException

**Comment by neilmulhy** [comment]
Looking up the latest error, it appears to be a timeout issue.

I can re-create the error by setting the timeout to 100 in the test email:
client.Timeout = 100;

There isn't anything in the code chain that alters the timeout anywhere or something that causes a delay?

**Comment by neilmulhy** [comment]
Resolved the issue. The nlog.config example that I'd picked up had the timeout property set to 1000. I've increased it and I now get emails when an error is enountered!  Thanks for your help @304NotModified

**Comment by 304NotModified** [comment]
Great work! Great news! 

So changing the default timeout is a good idea I guess?

**Comment by neilmulhy** [comment]
The default in your MailTarget file is fine.

If I remove the Timeout attribute from the nlog.config, it works. I can't recall where I got my example nlog.config file from but as long as the timeout is set 1200 or more or removed, it will work with office 365.

**Comment by 304NotModified** [comment]
this was done in 2.1 - so close
