### ISSUE TITLE
Make compatible with MailKit version 3

### ISSUE THREAD

**Issue by Trapulo** [NLog/NLog.MailKit#134]
Hi,
I've a problem with Mail Target. It reports:

> Exception: System.MissingMethodException: Method not found: Void MailKit.MailTransport.Send

full:
```
2022-01-12 08:57:48.0251 Error Mail Target[sendEmail]: Error has been raised. Exception: System.MissingMethodException: Method not found: 'Void MailKit.MailTransport.Send(MimeKit.MimeMessage, System.Threading.CancellationToken, MailKit.ITransferProgress)'.
   at NLog.MailKit.MailTarget.ProcessSingleMailMessage(IList`1 events)
   at NLog.MailKit.MailTarget.Write(IList`1 logEvents)
   at NLog.MailKit.MailTarget.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
```

I cannot explain why. I've MailKit.dll 3.0.0

The project is ASP.NET 6.0, with NLog.MailKit 4.0.0.4073 and NLog 4.7.13.493

Any idea?
thanks

**Comment by 304NotModified** [comment]
Yes, MailKit 3 is using [semver](https://semver.org/)(we also). So it isn't safe to mix major versions.

NLog.MailKit is build on MailKit 2- you could see that here:

![image](https://user-images.githubusercontent.com/5808377/149155996-df4cd17b-1715-414e-bbe9-efd8b5864253.png)


So it's not compatible with MailKit 3 yet

**Comment by 304NotModified** [comment]
Pull request accepted :)

**Comment by LadislavBohm** [comment]
Made a PR for this #135

**Comment by 304NotModified** [comment]
Thx!

**Comment by 304NotModified** [comment]
4.1 has been released! (currently indexing) Thanks for the PR!

https://www.nuget.org/packages/NLog.MailKit/4.1.0

**Comment by LadislavBohm** [comment]
Super fast work, thanks for releasing it so quickly.

**Comment by 304NotModified** [comment]
Thanks for the confirmation:)
