### ISSUE TITLE
Can't make it work with AWS SES

### ISSUE THREAD

**Issue by d668** [NLog/NLog.MailKit#62]
So I checked and SMTP settings are fine, but when I copy them to nlog file it doesn't work

```
<?xml version="1.0" encoding="utf-8" ?>
<!-- XSD manual extracted from package NLog.Schema: https://www.nuget.org/packages/NLog.Schema-->
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xsi:schemaLocation="NLog NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogFile="${currentdir}/internal.log"
      internalLogLevel="Info"
      throwExceptions="true"
      >

  <targets>
    <target xsi:type="File" name="target1" fileName="${currentdir}/log.log"
            layout="${date}|${level:uppercase=true}|${message} ${exception}|${logger}|${all-event-properties}" />
    <target xsi:type="Console" name="target2"
            layout="${date}|${level:uppercase=true}|${message} ${exception}|${logger}|${all-event-properties}" />

    <target name="target3" xsi:type="Mail"
           smtpServer="email-smtp.us-east-1.amazonaws.com"
           smtpPort="587"
           smtpAuthentication="Basic"
           smtpUserName="xx"
           smtpPassword="xx"
           enableSsl="true"
           from="logger@xxx.com"
           to="me@gmail.com"
            layout="${time} - ${level} - ${message}"
            secureSocketOption="StartTls" or "None", doesn't work
 
          />
  </targets>

  <rules>
    <logger name="*" minLevel="Trace" writeTo="target1,target3" />
  </rules>
  <extensions>
    <add assembly="NLog.MailKit"/>
  </extensions>
</nlog>
```

and in Main 

```
Logger logger = LogManager.GetCurrentClassLogger();
logger.Error("Program started");
```

```
Unhandled Exception: MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

One possibility is that you are trying to connect to a port which does not support SSL/TLS.

The other possibility is that the SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions. ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at NLog.MailKit.MailTarget.ProcessSingleMailMessage(IList`1 events)
   at NLog.MailKit.MailTarget.Write(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory factory)
   at Program.Main(String[] args) in C:\xxx\Program.cs:line 97
```

**Comment by 304NotModified** [comment]
Hi

Are you sure its not one of these issues?

> The other possibility is that the SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

If not, then 
I would recommend to test with secureSocketOption=StartTls when 
enableSsl="true" is removed. 

Ssl != startls. 

If not working, try other port numbers.

**Comment by d668** [comment]
OK this works 
```
   <target name="target3" xsi:type="Mail"
           smtpServer="email-smtp.us-east-1.amazonaws.com"
           smtpPort="587"
           smtpAuthentication="Basic"
           smtpUserName="xxx"
           smtpPassword="xxx"
           from="logger@xxx.com"
           to="me@gmail.com"
           secureSocketOption="StartTls"
            skipCertificateValidation="true"
          />
```

Thanks!!

**Comment by JohnLBevan** [comment]
To help others hitting the same, the fix d668 does above is to not specify useSsl, whilst setting secureSocketOption to StartTls and port to 587.  This, along with many other useful tips, is explained here: https://dotnetcoretutorials.com/2018/03/18/common-errors-sending-email-mailkit/
