### ISSUE TITLE
NotSupportedException: Parameter secureSocketOption not supported on MailTarget

### ISSUE THREAD

**Issue by westner** [NLog/NLog.MailKit#78]
Hello,

I get the error

NotSupportedException: Parameter secureSocketOption not supported on MailTarget

when using nlog.mailkit.

If I remove the property mails could be send without problem.

So the nlog/nlog.mailkit is working in general but what is the problem with the property?

Mailkit.dll is 2.5.2.0
NLog.dll 4.6.8
Nlog.Mailit.dll 3.1

**Comment by 304NotModified** [comment]
Are you using

```xml
<extensions>
    <add assembly="NLog.MailKit"/>
</extensions>
```

In you config? It looks like it's loading the other mailtarget (without mailkit)

**Comment by westner** [comment]
It is. As I wrote if I remove the secureSocketOption than sending mail works.

My nlog.config looks like

<?xml version="1.0" encoding="UTF-8"?>
  <nlog throwExceptions="true" xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <extensions>
    <add assembly="NLog.MailKit"/>
  </extensions>
  <targets>
    <target name="systemlog" xsi:type="Database" connectionStringName="RISConnectionString" commandText="insert into log_system(time_stamp,customername,url,action,ip,level,message)Values(@time_stamp,@customername,@url,@action,@ip,@level,@message)">
      <parameter name="time_stamp" layout="${date:format=d\.MM\.yyyy HH\:mm\:ss}"/>
      <parameter name="customername" layout="${mdc:customername}"/>
      <parameter name="url" layout="${mdc:url}"/>
      <parameter name="action" layout="${mdc:action}"/>
      <parameter name="ip" layout="${mdc:remote_addr}"/>
      <parameter name="level" layout="${level:uppercase=true}"/>
      <parameter name="message" layout="${message}"/>
    </target>
    <target name="userlog" xsi:type="Database" connectionStringName="RISConnectionString" commandText="insert into log_useraccess(time_stamp,customername,url,ip,risusername,message)Values(@time_stamp,@customername,@url,@ip,@risusername,@message)">
      <parameter name="time_stamp" layout="${date:format=d\.MM\.yyyy HH\:mm\:ss}"/>
      <parameter name="customername" layout="${mdc:customername}"/>
      <parameter name="url" layout="${mdc:url}"/>
      <parameter name="ip" layout="${mdc:remote_addr}"/>
      <parameter name="risusername" layout="${mdc:risusername}"/>
      <parameter name="message" layout="${message}"/>
    </target>

    <target name="mail" xsi:type="Mail"
         smtpAuthentication="Basic"
         smtpServer="xxxx"
         smtpPort="465"
         enableSsl="true"
         secureSocketOption="SslOnConnect"
         subject="RIS-Fehlerbenachrichtigung von ${mdc:customername}"
         from="xxxx"
         body="${message}"
         to="xxxx"
         smtpUserName="xxxx"
         smtpPassword="xxxx"
    />

    <target name="file" xsi:type="File" fileName="${basedir}/Logs/log.txt" layout="${date:format=d\.MM\.yyyy HH\:mm}|${mdc:customername}|${mdc:action}|${mdc:remote_addr}|${level:uppercase=true}|${message}" />
    <target name="debugfile" xsi:type="File" fileName="${basedir}/Logs/debuglog.txt" layout="${date:format=d\.MM\.yyyy HH\:mm}|${mdc:customername}|${mdc:action}|${mdc:remote_addr}|${level:uppercase=true}|${message}" />
    <target name="null" xsi:type="Null" layout="${message}" formatMessage="true" />
  </targets>
  <rules>
    
    <logger name="user" writeTo="userlog"/>
    <logger name="system" writeTo="systemlog"/>
    <logger name="system" levels="Error,Fatal" writeTo="mail"/>
  </rules>
 </nlog> 

In the target-mail I replaced the personal information with xxxxx

**Comment by westner** [comment]
Hello,

could anybody reproduce this problem or have a suggestion how to fix this?

Greetings

Stefan

**Comment by 304NotModified** [comment]
I haven't found time to test this. A small repo with reproduction would be great, then I could debug the issue.

**Comment by 304NotModified** [comment]
Hi, I made a demo case. 

I could not reproduce the issue :(

https://github.com/304NotModified/NLog-Demo-cases/tree/nlog.mailkit-notsupported/NLogMailkit/NLogMailKitConsole

Tested it net472 and net48

I get this, so it tries to connect:

```
System.Net.Sockets.SocketException
  HResult=0x80004005
  Message=No such host is known
  Source=System
  StackTrace:
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.SocketUtils.<ConnectAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.SocketUtils.<ConnectAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.MailService.<ConnectSocket>d__48.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.<ConnectAsync>d__74.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NLog.MailKit.MailTarget.ProcessSingleMailMessage(IList`1 events)
   at NLog.MailKit.MailTarget.Write(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.Error(String message)
   at NLogMailKitConsole.Program.Main(String[] args) in D:\github\304NotModified\NLog-Demo-cases\NLogMailkit\NLogMailKitConsole\NLogMailKitConsole\Program.cs:line 11

  This exception was originally thrown at this call stack:
	System.Net.Dns.HostResolutionEndHelper(System.IAsyncResult)
	System.Net.Dns.EndGetHostAddresses(System.IAsyncResult)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	MailKit.Net.SocketUtils.ConnectAsync(string, int, System.Net.IPEndPoint, bool, System.Threading.CancellationToken)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	MailKit.Net.SocketUtils.ConnectAsync(string, int, System.Net.IPEndPoint, int, bool, System.Threading.CancellationToken)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...
    [Call Stack Truncated]

```

![image](https://user-images.githubusercontent.com/5808377/77965772-09c06300-72e2-11ea-85ab-b03199ba2003.png)

**Comment by 304NotModified** [comment]
I get this internal log, please share yours:

```
2020-03-30 23:57:45.7029 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2020-03-30 23:57:45.7727 Debug Found assembly location directory: 'D:\github\304NotModified\NLog-Demo-cases\NLogMailkit\NLogMailKitConsole\NLogMailKitConsole\bin\Debug\net48' (NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c)
2020-03-30 23:57:45.7727 Debug Search for auto loading files in location: D:\github\304NotModified\NLog-Demo-cases\NLogMailkit\NLogMailKitConsole\NLogMailKitConsole\bin\Debug\net48
2020-03-30 23:57:45.7727 Debug Start auto loading, location: D:\github\304NotModified\NLog-Demo-cases\NLogMailkit\NLogMailKitConsole\NLogMailKitConsole\bin\Debug\net48
2020-03-30 23:57:45.7906 Info Auto loading assembly file: D:\github\304NotModified\NLog-Demo-cases\NLogMailkit\NLogMailKitConsole\NLogMailKitConsole\bin\Debug\net48\NLog.MailKit.dll
2020-03-30 23:57:45.7906 Info Loading assembly file: D:\github\304NotModified\NLog-Demo-cases\NLogMailkit\NLogMailKitConsole\NLogMailKitConsole\bin\Debug\net48\NLog.MailKit.dll
2020-03-30 23:57:45.8056 Info NLog.MailKit, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 1.0.243. Product version: 3.1.
2020-03-30 23:57:45.8056 Debug ScanAssembly('NLog.MailKit, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2020-03-30 23:57:45.8176 Info Auto loading assembly file: D:\github\304NotModified\NLog-Demo-cases\NLogMailkit\NLogMailKitConsole\NLogMailKitConsole\bin\Debug\net48\NLog.MailKit.dll succeeded!
2020-03-30 23:57:45.8176 Debug Auto loading done
2020-03-30 23:57:45.8176 Info Message Template Auto Format enabled
2020-03-30 23:57:45.8345 Info Loading assembly: NLog.MailKit
2020-03-30 23:57:45.8345 Debug ScanAssembly('NLog.MailKit, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2020-03-30 23:57:45.8565 Trace FindReachableObject<NLog.Internal.IRenderable>:
2020-03-30 23:57:45.8634 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2020-03-30 23:57:45.8634 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2020-03-30 23:57:45.8794 Trace Wrapping LevelLayoutRenderer with UppercaseLayoutRendererWrapper
2020-03-30 23:57:45.8794 Trace FindReachableObject<NLog.Internal.IRenderable>:
2020-03-30 23:57:45.8794 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2020-03-30 23:57:45.8794 Trace FindReachableObject<NLog.Internal.IRenderable>:
2020-03-30 23:57:45.8974 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
2020-03-30 23:57:45.8974 Trace  Scanning Property Inner 'SimpleLayout=Layout Renderer: ${level}' NLog.Layouts
2020-03-30 23:57:45.9143 Trace  Scanning SimpleLayout 'SimpleLayout=Layout Renderer: ${level}'
2020-03-30 23:57:45.9143 Trace   Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:45.9143 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2020-03-30 23:57:45.9283 Trace FindReachableObject<NLog.Internal.IRenderable>:
2020-03-30 23:57:45.9283 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
2020-03-30 23:57:45.9283 Trace FindReachableObject<NLog.Internal.IRenderable>:
2020-03-30 23:57:45.9432 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2020-03-30 23:57:45.9432 Trace FindReachableObject<NLog.Internal.IRenderable>:
2020-03-30 23:57:45.9432 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2020-03-30 23:57:45.9432 Trace FindReachableObject<NLog.Internal.IRenderable>:
2020-03-30 23:57:45.9602 Trace Scanning NewLineLayoutRenderer 'Layout Renderer: ${newline}'
2020-03-30 23:57:45.9602 Trace FindReachableObject<NLog.Internal.IRenderable>:
2020-03-30 23:57:45.9602 Trace Scanning MachineNameLayoutRenderer 'Layout Renderer: ${machinename}'
2020-03-30 23:57:45.9761 Debug Setting 'MailTarget.name' to 'mail'
2020-03-30 23:57:45.9761 Debug Setting 'MailTarget.smtpAuthentication' to 'Basic'
2020-03-30 23:57:45.9891 Debug Setting 'MailTarget.smtpServer' to 'xxxx'
2020-03-30 23:57:45.9891 Debug Setting 'MailTarget.smtpPort' to '465'
2020-03-30 23:57:45.9891 Debug Setting 'MailTarget.enableSsl' to 'true'
2020-03-30 23:57:46.0041 Debug Setting 'MailTarget.secureSocketOption' to 'SslOnConnect'
2020-03-30 23:57:46.0041 Debug Setting 'MailTarget.subject' to 'RIS-Fehlerbenachrichtigung von ${mdc:customername}'
2020-03-30 23:57:46.0041 Debug Setting 'MdcLayoutRenderer.Item' to 'customername'
2020-03-30 23:57:46.0041 Trace FindReachableObject<NLog.Internal.IRenderable>:
2020-03-30 23:57:46.0220 Trace Scanning MdcLayoutRenderer 'Layout Renderer: ${mdc}'
2020-03-30 23:57:46.0220 Debug Setting 'MailTarget.from' to 'xxxx'
2020-03-30 23:57:46.0220 Debug Setting 'MailTarget.body' to '${message}'
2020-03-30 23:57:46.0360 Trace FindReachableObject<NLog.Internal.IRenderable>:
2020-03-30 23:57:46.0360 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2020-03-30 23:57:46.0360 Debug Setting 'MailTarget.to' to 'xxxx'
2020-03-30 23:57:46.0360 Debug Setting 'MailTarget.smtpUserName' to 'xxxx'
2020-03-30 23:57:46.0569 Debug Setting 'MailTarget.smtpPassword' to 'xxxx'
2020-03-30 23:57:46.0569 Info Adding target MailTarget(Name=mail)
2020-03-30 23:57:46.0669 Debug Registered target mail: NLog.MailKit.MailTarget
2020-03-30 23:57:46.0669 Trace ParseRulesElement
2020-03-30 23:57:46.0948 Debug Unused target checking is started... Rule Count: 1, Target Count: 1
2020-03-30 23:57:46.1008 Debug Unused target checking is completed. Total Rule Count: 1, Total Target Count: 1, Unused Target Count: 0
2020-03-30 23:57:46.1148 Debug --- NLog configuration dump ---
2020-03-30 23:57:46.1148 Debug Targets:
2020-03-30 23:57:46.1148 Debug Mail Target[mail]
2020-03-30 23:57:46.1307 Debug Rules:
2020-03-30 23:57:46.1307 Debug logNamePattern: (:All) levels: [ Error Fatal ] appendTo: [ mail ]
2020-03-30 23:57:46.1307 Debug --- End of NLog configuration dump ---
2020-03-30 23:57:46.1487 Trace FindReachableObject<System.Object>:
2020-03-30 23:57:46.1487 Trace Scanning LoggingRule 'logNamePattern: (:All) levels: [ Error Fatal ] appendTo: [ mail ]'
2020-03-30 23:57:46.1487 Trace  Scanning Property Targets 'System.Collections.Generic.List`1[NLog.Targets.Target]' System.Collections.Generic
2020-03-30 23:57:46.1626 Trace  Scanning MailTarget 'Mail Target[mail]'
2020-03-30 23:57:46.1626 Trace   Scanning Property From ''xxxx'' NLog.Layouts
2020-03-30 23:57:46.1626 Trace   Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.1626 Trace    Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.1806 Trace    Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2020-03-30 23:57:46.1806 Trace   Scanning Property To ''xxxx'' NLog.Layouts
2020-03-30 23:57:46.1806 Trace   Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.1956 Trace    Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.1956 Trace    Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2020-03-30 23:57:46.1956 Trace   Scanning Property Subject ''RIS-Fehlerbenachrichtigung von ${mdc:customername}'' NLog.Layouts
2020-03-30 23:57:46.2095 Trace   Scanning SimpleLayout ''RIS-Fehlerbenachrichtigung von ${mdc:customername}''
2020-03-30 23:57:46.2095 Trace    Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.2095 Trace    Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2020-03-30 23:57:46.2235 Trace    Scanning MdcLayoutRenderer 'Layout Renderer: ${mdc}'
2020-03-30 23:57:46.2235 Trace   Scanning Property Body ''${message}'' NLog.Layouts
2020-03-30 23:57:46.2235 Trace   Scanning SimpleLayout ''${message}''
2020-03-30 23:57:46.2384 Trace    Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.2384 Trace    Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2020-03-30 23:57:46.2384 Trace   Scanning Property Encoding 'System.Text.UTF8Encoding' System.Text
2020-03-30 23:57:46.2384 Trace   Scanning Property SmtpServer ''xxxx'' NLog.Layouts
2020-03-30 23:57:46.2584 Trace   Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.2584 Trace    Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.2584 Trace    Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2020-03-30 23:57:46.2724 Trace   Scanning Property SmtpUserName ''xxxx'' NLog.Layouts
2020-03-30 23:57:46.2724 Trace   Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.2724 Trace    Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.2893 Trace    Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2020-03-30 23:57:46.2893 Trace   Scanning Property SmtpPassword ''xxxx'' NLog.Layouts
2020-03-30 23:57:46.2893 Trace   Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.3043 Trace    Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.3043 Trace    Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2020-03-30 23:57:46.3043 Trace   Scanning Property Layout ''${message}'' NLog.Layouts
2020-03-30 23:57:46.3202 Trace  Scanning Property ChildRules 'System.Collections.Generic.List`1[NLog.Config.LoggingRule]' System.Collections.Generic
2020-03-30 23:57:46.3202 Trace  Scanning Property Filters 'System.Collections.Generic.List`1[NLog.Filters.Filter]' System.Collections.Generic
2020-03-30 23:57:46.3202 Info Found 17 configuration items
2020-03-30 23:57:46.3362 Trace Initializing Layout Renderer: ${literal}
2020-03-30 23:57:46.3362 Trace Initializing 'xxxx'
2020-03-30 23:57:46.3491 Trace FindReachableObject<System.Object>:
2020-03-30 23:57:46.3491 Trace Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.3491 Trace  Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.3641 Trace  Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2020-03-30 23:57:46.3641 Trace Initializing Layout Renderer: ${literal}
2020-03-30 23:57:46.3641 Trace Initializing 'xxxx'
2020-03-30 23:57:46.3831 Trace FindReachableObject<System.Object>:
2020-03-30 23:57:46.3831 Trace Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.3831 Trace  Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.3981 Trace  Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2020-03-30 23:57:46.3981 Trace Initializing Layout Renderer: ${literal}
2020-03-30 23:57:46.3981 Trace Initializing 'xxxx'
2020-03-30 23:57:46.4140 Trace FindReachableObject<System.Object>:
2020-03-30 23:57:46.4140 Trace Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.4140 Trace  Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.4289 Trace  Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2020-03-30 23:57:46.4289 Trace Initializing Layout Renderer: ${message}
2020-03-30 23:57:46.4289 Trace Initializing '${message}'
2020-03-30 23:57:46.4439 Trace FindReachableObject<System.Object>:
2020-03-30 23:57:46.4439 Trace Scanning SimpleLayout ''${message}''
2020-03-30 23:57:46.4439 Trace  Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.4589 Trace  Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2020-03-30 23:57:46.4589 Trace Initializing Layout Renderer: ${mdc}
2020-03-30 23:57:46.4589 Trace Initializing Layout Renderer: ${literal}
2020-03-30 23:57:46.4748 Trace Initializing 'RIS-Fehlerbenachrichtigung von ${mdc:customername}'
2020-03-30 23:57:46.4748 Trace FindReachableObject<System.Object>:
2020-03-30 23:57:46.4748 Trace Scanning SimpleLayout ''RIS-Fehlerbenachrichtigung von ${mdc:customername}''
2020-03-30 23:57:46.4908 Trace  Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.4908 Trace  Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2020-03-30 23:57:46.4908 Trace  Scanning MdcLayoutRenderer 'Layout Renderer: ${mdc}'
2020-03-30 23:57:46.5067 Trace Initializing Layout Renderer: ${literal}
2020-03-30 23:57:46.5067 Trace Initializing 'xxxx'
2020-03-30 23:57:46.5067 Trace FindReachableObject<System.Object>:
2020-03-30 23:57:46.5217 Trace Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.5217 Trace  Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.5217 Trace  Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2020-03-30 23:57:46.5366 Trace Initializing Layout Renderer: ${literal}
2020-03-30 23:57:46.5366 Trace Initializing 'xxxx'
2020-03-30 23:57:46.5366 Trace FindReachableObject<System.Object>:
2020-03-30 23:57:46.5556 Trace Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.5556 Trace  Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2020-03-30 23:57:46.5666 Trace  Scanning LiteralLayoutRenderer 'Layout Renderer: ${literal}'
2020-03-30 23:57:46.5666 Trace Initializing Mail Target[mail]
2020-03-30 23:57:46.5666 Debug Init mailtarget with mailkit
2020-03-30 23:57:46.5845 Trace FindReachableObject<NLog.Layouts.Layout>:
2020-03-30 23:57:46.5845 Trace Scanning MailTarget 'Mail Target[mail]'
2020-03-30 23:57:46.5845 Trace  Scanning Property SmtpServer ''xxxx'' NLog.Layouts
2020-03-30 23:57:46.5995 Trace  Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.5995 Trace  Scanning Property Subject ''RIS-Fehlerbenachrichtigung von ${mdc:customername}'' NLog.Layouts
2020-03-30 23:57:46.5995 Trace  Scanning SimpleLayout ''RIS-Fehlerbenachrichtigung von ${mdc:customername}''
2020-03-30 23:57:46.6144 Trace  Scanning Property From ''xxxx'' NLog.Layouts
2020-03-30 23:57:46.6144 Trace  Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.6144 Trace  Scanning Property Body ''${message}'' NLog.Layouts
2020-03-30 23:57:46.6144 Trace  Scanning SimpleLayout ''${message}''
2020-03-30 23:57:46.6334 Trace  Scanning Property To ''xxxx'' NLog.Layouts
2020-03-30 23:57:46.6334 Trace  Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.6334 Trace  Scanning Property SmtpUserName ''xxxx'' NLog.Layouts
2020-03-30 23:57:46.6483 Trace  Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.6483 Trace  Scanning Property SmtpPassword ''xxxx'' NLog.Layouts
2020-03-30 23:57:46.6483 Trace  Scanning SimpleLayout ''xxxx''
2020-03-30 23:57:46.6633 Trace  Scanning Property Encoding 'System.Text.UTF8Encoding' System.Text
2020-03-30 23:57:46.6633 Trace  Scanning Property Layout ''${message}'' NLog.Layouts
2020-03-30 23:57:46.6633 Trace  Scanning SimpleLayout ''${message}''
2020-03-30 23:57:46.6793 Trace Mail Target[mail] has 8 layouts
2020-03-30 23:57:46.6793 Info Configuration initialized.
2020-03-30 23:57:46.6793 Info NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 4.6.8.10751. Product version: 4.6.8.
2020-03-30 23:57:46.6982 Debug Targets for logger1 by level:
2020-03-30 23:57:46.6982 Debug Trace =>
2020-03-30 23:57:46.7132 Debug Debug =>
2020-03-30 23:57:46.7132 Debug Info =>
2020-03-30 23:57:46.7231 Debug Warn =>
2020-03-30 23:57:46.7231 Debug Error => mail
2020-03-30 23:57:46.7231 Debug Fatal => mail
2020-03-30 23:57:46.8638 Debug Sending mail to xxxx using xxxx:465 (socket option=SslOnConnect)
2020-03-30 23:57:46.8638 Trace   Subject: 'RIS-Fehlerbenachrichtigung von'
2020-03-30 23:57:46.8638 Trace   From: 'xxxx'
2020-03-30 23:57:49.1746 Error Error sending mail. Exception: System.Net.Sockets.SocketException (0x80004005): No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.SocketUtils.<ConnectAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.SocketUtils.<ConnectAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.MailService.<ConnectSocket>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.<ConnectAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NLog.MailKit.MailTarget.ProcessSingleMailMessage(IList`1 events)

```
See https://github.com/nlog/nlog/wiki/Internal-logging

**Comment by westner** [comment]
Hello, 
thanks for your example. It worked on my side.
I double-checked all in our webapplication, updated all assemblies, references and so on and now it is working.
At least the whole thing was caused by a assembly-mismatch in our project.
It was not a bug in the nlog.mailkit.
Thanks angain and sorry for the issue.

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
