### ISSUE TITLE
From attribute doesn't support 'Dont Reply <do_not_reply@domain.com>' format

### ISSUE THREAD

**Issue by bacr** [NLog/NLog.MailKit#8]
Sample:
```xml
<target name="email" type="Mail" to="recipient@google.com" from="Dont Reply &lt;do_not_reply@domain.com&gt;" subject="Error: ${message} ${exception:format=message}"
            body="${message} ${exception:format=tostring}" smtpServer="smtp.server" smtpPort="25" smtpAuthentication="Basic" smtpUserName="user" smtpPassword="pass" />
````

Exception:
```
MimeKit.ParseException: Invalid addr-spec token at offset 0
   at MimeKit.InternetAddress.TryParseAddrspec(Byte[] text, Int32& index, Int32 endIndex, Byte[] sentinels, Boolean throwOnError, String& addrspec, Int32& at)
   at MimeKit.MailboxAddress.set_Address(String value)
   at MimeKit.MailboxAddress..ctor(Encoding encoding, String name, String address)
   at NLog.MailKit.MailTarget.CreateMailMessage(LogEventInfo lastEvent, String body)
   at NLog.MailKit.MailTarget.ProcessSingleMailMessage(IList`1 events)
```

**Comment by 304NotModified** [comment]
Isn't this a XML encoding problem?

**Comment by 304NotModified** [comment]
Please post your config

**Comment by bacr** [comment]
Added sample config

**Comment by bacr** [comment]
Probably need to use [MailboxAddress.Parse](http://www.mimekit.net/docs/html/M_MimeKit_MailboxAddress_Parse_7.htm)

**Comment by 304NotModified** [comment]
Thanks! Really helpful! Need to add some tests and then it's Done

**Comment by 304NotModified** [comment]
@bacr 
could you please test with https://www.nuget.org/packages/NLog.MailKit/1.0.0-dev20170531 ?

**Comment by 304NotModified** [comment]
if it all works well, I will release 1.0 RTM

**Comment by 304NotModified** [comment]
as the unit test is working now, this is resolved.
